package com.devtreelocation.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "source_location_table") // SourceLocation Entity represents a table within the database.
data class SourceLocation(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val locationId: String,
    val locationName: String,
    val locationAddress: String,
    val locationLat: Double,
    val locationLong: Double
) : Parcelable